name: Get Environment Configuration
description: Get AWS and deployment configuration for the specified environment

inputs:
  env:
    description: Environment name (production)
    required: true

outputs:
  aws_account_id:
    description: "AWS account ID for the environment"
    value: ${{ steps.set_config.outputs.aws_account_id }}
  aws_region:
    description: "AWS region for the environment"
    value: ${{ steps.set_config.outputs.aws_region }}
  ecr_registry:
    description: "ECR registry URL"
    value: ${{ steps.set_config.outputs.ecr_registry }}
  ecr_repo:
    description: "ECR repository name"
    value: ${{ steps.set_config.outputs.ecr_repo }}
  role_name:
    description: "AWS IAM role name for deployment"
    value: ${{ steps.set_config.outputs.role_name }}
  cluster_name:
    description: "ECS cluster name"
    value: ${{ steps.set_config.outputs.cluster_name }}
  service_name:
    description: "ECS service name"
    value: ${{ steps.set_config.outputs.service_name }}

runs:
  using: "composite"
  steps:
    - name: Set environment configuration
      id: set_config
      shell: bash
      run: |
        # Set AWS region (default: us-west-2)
        AWS_REGION="us-west-2"
        echo "aws_region=$AWS_REGION" >> $GITHUB_OUTPUT

        AWS_ACCOUNT_ID="525896657660"
        ECR_REPO="better-chatbot"
        CLUSTER_NAME="tools-prod"
        SERVICE_NAME="better-chatbot"
        ROLE_NAME="deploy-better-chatbot"

        ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

        echo "aws_account_id=$AWS_ACCOUNT_ID" >> $GITHUB_OUTPUT
        echo "ecr_registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT
        echo "ecr_repo=$ECR_REPO" >> $GITHUB_OUTPUT
        echo "cluster_name=$CLUSTER_NAME" >> $GITHUB_OUTPUT
        echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
        echo "role_name=$ROLE_NAME" >> $GITHUB_OUTPUT

        echo "Configuration for production environment"
        echo "  AWS Account: $AWS_ACCOUNT_ID"
        echo "  ECR Registry: $ECR_REGISTRY"
        echo "  ECR Repo: $ECR_REPO"
        echo "  Cluster: $CLUSTER_NAME"
        echo "  Service: $SERVICE_NAME"
        echo "  Role: $ROLE_NAME"
